from datetime import datetime
from decimal import Decimal
from uuid import UUID

from sqlalchemy import BigInteger, Boolean, CHAR, CheckConstraint, DateTime, ForeignKey, Index, Integer, Numeric, SmallInteger, String, Text, UniqueConstraint, text
from sqlalchemy.dialects.postgresql import JSONB, UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column

from app.infrastructure.database import Base

SCHEMA = "ai_knowledge"
def uid(): return mapped_column(PGUUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"))
def ts(): return mapped_column(DateTime(timezone=True), server_default=text("now()"))


class KnowledgeBase(Base):
    __tablename__="knowledge_bases"; __table_args__=(CheckConstraint("visibility IN ('public','department','private')",name="ck_knowledge_bases_visibility"),CheckConstraint("owner_user_id IS NOT NULL OR owner_department IS NOT NULL",name="ck_knowledge_bases_owner"),CheckConstraint("chunk_size BETWEEN 100 AND 2000",name="ck_knowledge_bases_chunk_size"),CheckConstraint("chunk_overlap BETWEEN 0 AND 500 AND chunk_overlap < chunk_size",name="ck_knowledge_bases_chunk_overlap"),Index("uq_knowledge_bases_name_active",text("lower(name)"),unique=True,postgresql_where=text("deleted_at IS NULL")),{"schema":SCHEMA})
    id:Mapped[UUID]=uid(); name:Mapped[str]=mapped_column(String(100)); description:Mapped[str|None]=mapped_column(String(500)); visibility:Mapped[str]=mapped_column(String(16),server_default=text("'private'")); owner_user_id:Mapped[UUID|None]=mapped_column(PGUUID(as_uuid=True)); owner_department:Mapped[str|None]=mapped_column(String(100)); embedding_model:Mapped[str]=mapped_column(String(100),server_default=text("'bge-small-zh-v1.5'")); chunk_size:Mapped[int]=mapped_column(Integer,server_default=text("500")); chunk_overlap:Mapped[int]=mapped_column(Integer,server_default=text("80")); collection_name:Mapped[str]=mapped_column(String(80),unique=True); version:Mapped[int]=mapped_column(Integer,server_default=text("1")); created_by:Mapped[UUID]=mapped_column(PGUUID(as_uuid=True)); created_at:Mapped[datetime]=ts(); updated_at:Mapped[datetime]=ts(); deleted_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))

class KnowledgeBaseMember(Base):
    __tablename__="knowledge_base_members"; __table_args__=(CheckConstraint("access_level IN ('viewer','editor','owner')",name="ck_knowledge_base_members_access"),Index("ix_knowledge_base_members_user","user_id","access_level"),{"schema":SCHEMA})
    knowledge_base_id:Mapped[UUID]=mapped_column(PGUUID(as_uuid=True),ForeignKey(f"{SCHEMA}.knowledge_bases.id",ondelete="CASCADE"),primary_key=True); user_id:Mapped[UUID]=mapped_column(PGUUID(as_uuid=True),primary_key=True); access_level:Mapped[str]=mapped_column(String(16)); granted_by:Mapped[UUID]=mapped_column(PGUUID(as_uuid=True)); granted_at:Mapped[datetime]=ts()

class Document(Base):
    __tablename__="documents"; __table_args__=(CheckConstraint("file_size_bytes BETWEEN 1 AND 20971520",name="ck_documents_file_size"),CheckConstraint("status IN ('pending','processing','ready','published','inactive','failed','deleted')",name="ck_documents_status"),Index("uq_documents_hash_active","knowledge_base_id","file_sha256",unique=True,postgresql_where=text("deleted_at IS NULL AND status <> 'deleted'")),Index("ix_documents_kb_status","knowledge_base_id","status",text("updated_at DESC"),postgresql_where=text("deleted_at IS NULL")),{"schema":SCHEMA})
    id:Mapped[UUID]=uid(); knowledge_base_id:Mapped[UUID]=mapped_column(PGUUID(as_uuid=True),ForeignKey(f"{SCHEMA}.knowledge_bases.id",ondelete="RESTRICT")); title:Mapped[str]=mapped_column(String(200)); original_file_name:Mapped[str]=mapped_column(String(255)); object_key:Mapped[str]=mapped_column(String(500),unique=True); mime_type:Mapped[str]=mapped_column(String(100)); file_size_bytes:Mapped[int]=mapped_column(BigInteger); file_sha256:Mapped[str]=mapped_column(CHAR(64)); status:Mapped[str]=mapped_column(String(20),server_default=text("'pending'")); document_version:Mapped[int]=mapped_column(Integer,server_default=text("1")); index_version:Mapped[int|None]=mapped_column(Integer); page_count:Mapped[int|None]=mapped_column(Integer); chunk_count:Mapped[int]=mapped_column(Integer,server_default=text("0")); published_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); inactive_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); expires_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); created_by:Mapped[UUID]=mapped_column(PGUUID(as_uuid=True)); version:Mapped[int]=mapped_column(Integer,server_default=text("1")); created_at:Mapped[datetime]=ts(); updated_at:Mapped[datetime]=ts(); deleted_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))

class IngestionJob(Base):
    __tablename__="ingestion_jobs"; __table_args__=(CheckConstraint("stage IN ('queued','parsing','cleaning','splitting','embedding','indexing','succeeded','failed')",name="ck_ingestion_jobs_stage"),CheckConstraint("progress BETWEEN 0 AND 100",name="ck_ingestion_jobs_progress"),Index("ix_ingestion_jobs_queue","stage","created_at",postgresql_where=text("stage NOT IN ('succeeded','failed')")),{"schema":SCHEMA})
    id:Mapped[UUID]=uid(); document_id:Mapped[UUID]=mapped_column(PGUUID(as_uuid=True),ForeignKey(f"{SCHEMA}.documents.id",ondelete="CASCADE")); celery_task_id:Mapped[str|None]=mapped_column(String(100),unique=True); stage:Mapped[str]=mapped_column(String(20),server_default=text("'queued'")); progress:Mapped[int]=mapped_column(SmallInteger,server_default=text("0")); attempt:Mapped[int]=mapped_column(Integer,server_default=text("1")); max_attempts:Mapped[int]=mapped_column(Integer,server_default=text("3")); error_code:Mapped[str|None]=mapped_column(String(100)); error_message:Mapped[str|None]=mapped_column(String(1000),repr=False); started_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); finished_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); created_by:Mapped[UUID]=mapped_column(PGUUID(as_uuid=True)); created_at:Mapped[datetime]=ts(); updated_at:Mapped[datetime]=ts()

class DocumentChunk(Base):
    __tablename__="document_chunks"; __table_args__=(UniqueConstraint("document_id","document_version","chunk_index"),CheckConstraint("clean_status IN ('clean','redacted','excluded')",name="ck_document_chunks_clean_status"),Index("ix_document_chunks_document","document_id","document_version","chunk_index"),{"schema":SCHEMA})
    id:Mapped[UUID]=uid(); document_id:Mapped[UUID]=mapped_column(PGUUID(as_uuid=True),ForeignKey(f"{SCHEMA}.documents.id",ondelete="CASCADE")); document_version:Mapped[int]=mapped_column(Integer); chunk_index:Mapped[int]=mapped_column(Integer); content:Mapped[str]=mapped_column(Text,repr=False); source_location:Mapped[str]=mapped_column(String(500)); page_number:Mapped[int|None]=mapped_column(Integer); token_count:Mapped[int]=mapped_column(Integer); content_sha256:Mapped[str]=mapped_column(CHAR(64),repr=False); clean_status:Mapped[str]=mapped_column(String(16),server_default=text("'clean'")); vector_id:Mapped[str]=mapped_column(String(100),unique=True); index_version:Mapped[int]=mapped_column(Integer); created_at:Mapped[datetime]=ts()

class Conversation(Base):
    __tablename__="conversations"; __table_args__=(CheckConstraint("status IN ('active','deleted')",name="ck_conversations_status"),Index("ix_conversations_user","user_id",text("updated_at DESC"),postgresql_where=text("deleted_at IS NULL")),{"schema":SCHEMA})
    id:Mapped[UUID]=uid(); user_id:Mapped[UUID]=mapped_column(PGUUID(as_uuid=True)); title:Mapped[str]=mapped_column(String(100),server_default=text("'新对话'")); status:Mapped[str]=mapped_column(String(16),server_default=text("'active'")); last_message_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); created_at:Mapped[datetime]=ts(); updated_at:Mapped[datetime]=ts(); deleted_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))

class Message(Base):
    __tablename__="messages"; __table_args__=(UniqueConstraint("conversation_id","sequence_no"),CheckConstraint("role IN ('user','assistant')",name="ck_messages_role"),CheckConstraint("status IN ('pending','streaming','completed','failed','cancelled','fallback')",name="ck_messages_status"),Index("ix_messages_conversation","conversation_id","sequence_no"),{"schema":SCHEMA})
    id:Mapped[UUID]=uid(); conversation_id:Mapped[UUID]=mapped_column(PGUUID(as_uuid=True),ForeignKey(f"{SCHEMA}.conversations.id",ondelete="CASCADE")); sequence_no:Mapped[int]=mapped_column(Integer); role:Mapped[str]=mapped_column(String(16)); status:Mapped[str]=mapped_column(String(16)); content:Mapped[str]=mapped_column(Text,server_default=text("''"),repr=False); reply_to_message_id:Mapped[UUID|None]=mapped_column(PGUUID(as_uuid=True),ForeignKey(f"{SCHEMA}.messages.id",ondelete="SET NULL")); model:Mapped[str|None]=mapped_column(String(100)); finish_reason:Mapped[str|None]=mapped_column(String(50)); prompt_tokens:Mapped[int|None]=mapped_column(Integer); completion_tokens:Mapped[int|None]=mapped_column(Integer); retrieval_confidence:Mapped[Decimal|None]=mapped_column(Numeric(6,5)); fallback_reason:Mapped[str|None]=mapped_column(String(200)); request_id:Mapped[str]=mapped_column(String(64)); error_code:Mapped[str|None]=mapped_column(String(100)); started_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); completed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); created_at:Mapped[datetime]=ts(); updated_at:Mapped[datetime]=ts()

class RetrievalRun(Base):
    __tablename__="retrieval_runs"; __table_args__=(CheckConstraint("jsonb_typeof(knowledge_base_ids)='array'",name="ck_retrieval_runs_kbs"),{"schema":SCHEMA})
    id:Mapped[UUID]=uid(); assistant_message_id:Mapped[UUID]=mapped_column(PGUUID(as_uuid=True),ForeignKey(f"{SCHEMA}.messages.id",ondelete="CASCADE"),unique=True); query_sha256:Mapped[str]=mapped_column(CHAR(64),repr=False); knowledge_base_ids:Mapped[list]=mapped_column(JSONB); top_k:Mapped[int]=mapped_column(Integer); score_threshold:Mapped[Decimal]=mapped_column(Numeric(6,5)); result_summary:Mapped[list]=mapped_column(JSONB,server_default=text("'[]'::jsonb")); duration_ms:Mapped[int]=mapped_column(Integer); created_at:Mapped[datetime]=ts()

class MessageCitation(Base):
    __tablename__="message_citations"; __table_args__=(UniqueConstraint("message_id","citation_no"),UniqueConstraint("message_id","chunk_id"),{"schema":SCHEMA})
    id:Mapped[UUID]=uid(); message_id:Mapped[UUID]=mapped_column(PGUUID(as_uuid=True),ForeignKey(f"{SCHEMA}.messages.id",ondelete="CASCADE")); citation_no:Mapped[int]=mapped_column(Integer); chunk_id:Mapped[UUID]=mapped_column(PGUUID(as_uuid=True),ForeignKey(f"{SCHEMA}.document_chunks.id",ondelete="RESTRICT")); document_id:Mapped[UUID]=mapped_column(PGUUID(as_uuid=True)); document_title:Mapped[str]=mapped_column(String(200)); source_location:Mapped[str]=mapped_column(String(500)); page_number:Mapped[int|None]=mapped_column(Integer); quote_excerpt:Mapped[str]=mapped_column(String(500)); relevance_score:Mapped[Decimal]=mapped_column(Numeric(6,5)); created_at:Mapped[datetime]=ts()

class MessageFeedback(Base):
    __tablename__="message_feedback"; __table_args__=(UniqueConstraint("message_id","user_id"),CheckConstraint("rating IN (-1,1)",name="ck_message_feedback_rating"),{"schema":SCHEMA})
    id:Mapped[UUID]=uid(); message_id:Mapped[UUID]=mapped_column(PGUUID(as_uuid=True),ForeignKey(f"{SCHEMA}.messages.id",ondelete="CASCADE")); user_id:Mapped[UUID]=mapped_column(PGUUID(as_uuid=True)); rating:Mapped[int]=mapped_column(SmallInteger); correction:Mapped[str|None]=mapped_column(String(1000)); created_at:Mapped[datetime]=ts(); updated_at:Mapped[datetime]=ts()

class LlmCall(Base):
    __tablename__="llm_calls"; __table_args__=(UniqueConstraint("message_id","attempt"),CheckConstraint("status IN ('started','completed','failed','cancelled')",name="ck_llm_calls_status"),{"schema":SCHEMA})
    id:Mapped[UUID]=uid(); message_id:Mapped[UUID]=mapped_column(PGUUID(as_uuid=True),ForeignKey(f"{SCHEMA}.messages.id",ondelete="CASCADE")); attempt:Mapped[int]=mapped_column(Integer,server_default=text("1")); provider:Mapped[str]=mapped_column(String(30),server_default=text("'deepseek'")); model:Mapped[str]=mapped_column(String(100)); provider_request_id:Mapped[str|None]=mapped_column(String(100)); thinking_enabled:Mapped[bool]=mapped_column(Boolean,server_default=text("false")); status:Mapped[str]=mapped_column(String(16)); finish_reason:Mapped[str|None]=mapped_column(String(50)); prompt_tokens:Mapped[int|None]=mapped_column(Integer); completion_tokens:Mapped[int|None]=mapped_column(Integer); first_token_ms:Mapped[int|None]=mapped_column(Integer); total_duration_ms:Mapped[int|None]=mapped_column(Integer); error_code:Mapped[str|None]=mapped_column(String(100)); created_at:Mapped[datetime]=ts(); finished_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
